version: '3.7'

services:
  db:
    image: mysql:5.7.24
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
    env_file: .env
    environment:
      RAILS_ENV: development
  frontend:
    build:
      context: ../products_front_end/
    depends_on:
      - app
    volumes:
      - ../products_front_end/:/app/
      - ../products_front_end/node_modules:/app/node_modules
    command: npm start
    ports:
      - "3001:3000"

volumes:
  db-data:
